# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        stages: [commit]
        language: system
        types: [python]
      - id: autopep8
        name: autopep8
        entry: make autopep8
        stages: [commit]
        language: system
        types: [python]    
      - id: test
        name: test
        entry: make test
        stages: [push]
        language: system
        types: [python]