# unless otherwise specified, hooks run on commit only
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: requirements-txt-fixer
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/timothycrosley/isort
    rev: 5.1.1
    hooks:
      - id: isort
  - repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
      - id: docformatter
        args: [--wrap-summaries,'120',--wrap-descriptions,'120',--pre-summary-newline,--in-place]
  # these hooks require the project's virtualenv so need to be local and language: system    
  - repo: local
    hooks:
      - id: check
        name: check
        entry: ./.pre-commit-check.sh
        stages: [push]
        language: system
        types: [python]
      - id: test
        name: test
        entry: make test
        stages: [push]
        language: system
        types: [python]
