#cloud-config
# Refresh the locally cached package listing from the network repository
repo_update: true
# apply all available upgrades (default is security)
repo_upgrade: security

groups:
  - docker: ec2-user

runcmd:
  - amazon-linux-extras install docker
  - systemctl start docker.service
