# example config, update this for your account and cp to ~/.asak/config

# tags added to ec2 instances during launch
additional_tags = { Owner = "alice@little.co", Project = "example project" }
default_profile = "syd"

[syd]
region = "ap-southeast-2"
key_name = "my-key"
iam_instance_profile_arn = "arn:aws:iam::123456789012:instance-profile/ec2_my_default"
vpc = { name = "public A", subnet = "subnet-12345678",  security_group = "sg-12345678901234567" }

[us]
region = "us-east-1"
key_name = "my-key-us"
iam_instance_profile_arn = "arn:aws:iam::123456789012:instance-profile/ec2_my_default"
vpc = { name = "private B", subnet = "subnet-87654321",  security_group = "sg-01234567123456789" }