name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install requirements
      run: |
        make install-reqs
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test